openapi: 3.0.3
info:
  title: GuestInfoSystemAPI
  version: 0.2.0
servers:
  # This is overriden by HOST_BASE_URL.
  # Localhost development url
  - url: http://localhost:10001/v0
paths:
  $ref: "./paths/index.yaml"
components:
  responses:
    $ref: "./responses/index.yaml"
  schemas:
    $ref: "./schemas/index.yaml"
